apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cryptopred

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      environment: dev
      component: api
    includeSelectors: true
