apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cryptopred

resources:
  - configmap.yaml
  - training-cronjob.yaml
  - prediction-deployment.yaml

labels:
  - pairs:
      environment: dev
      component: ml
    includeSelectors: true
