apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-historical
  namespace: cryptopred
  labels:
    app: candles-historical
    component: backfill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles-historical
  template:
    metadata:
      labels:
        app: candles-historical
        component: backfill
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: candles
          image: candles:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_INPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: TRADES_TOPIC
            - name: KAFKA_OUTPUT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: CANDLES_TOPIC
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: CANDLES_CONSUMER_GROUP
            - name: CANDLE_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: CANDLE_SECONDS
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
