apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cryptopred

resources:
  - configmap.yaml
  - trades-historical-deployment.yaml
  - candles-historical-deployment.yaml
  - technical-indicators-historical-deployment.yaml

labels:
  - pairs:
      environment: dev
      component: backfill
    includeSelectors: true
