apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-historical
  namespace: cryptopred
  labels:
    app: trades-historical
    component: backfill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-historical
  template:
    metadata:
      labels:
        app: trades-historical
        component: backfill
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: trades
          image: trades:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: TRADES_TOPIC
            - name: LIVE_OR_HISTORICAL
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: LIVE_OR_HISTORICAL
            - name: LAST_N_DAYS
              valueFrom:
                configMapKeyRef:
                  name: backfill-config
                  key: LAST_N_DAYS
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
